### ISSUE TITLE
Mongoid Validate Invalid Option

### ISSUE THREAD

**Issue by RickTheHat** [pelle/oauth-plugin#117]
gems/ruby-1.9.3-p125@rails323/gems/mongoid-2.4.9/lib/mongoid/relations/options.rb:41:in `block in validate!': Invalid option :include provided to relation :tokens. Valid options are: as, autosave, dependent, foreign_key, order, class_name, extend, inverse_class_name, inverse_of, name, relation, validate. (Mongoid::Errors::InvalidOptions)

I'm using all the latest versions here, maybe I'm too bleeding edge and need to step back my mongoid driver, or rails version. Any help would be appreciated.

**Comment by acellam** [comment]
I wondering if you ever rectified this error, i ran into it today
