### ISSUE TITLE
Stack level too deep error

### ISSUE THREAD

**Issue by banjarey** [pelle/oauth-plugin#119]
I've been trying to setup oauth_consumers, and while the setup itself was a breeze, I just can't seem to get anything to work. I keep getting the stack level too deep error, and I'm unable to point out from where it might be originating.

Anybody has faced similar issues in the past with oauth-plugin or can anybody help me with a clue ?

``` ruby
Processing by OauthConsumersController#show as HTML
  Parameters: {"id"=>"facebook"}

SystemStackError (stack level too deep):
  actionpack (3.2.3) lib/action_dispatch/middleware/reloader.rb:70
```

Thanks
Sanjay

**Comment by banjarey** [comment]
Sorry...problem at my end !

**Comment by michaelcho** [comment]
@banjarey I am having the same issue, do you remember what you did by any chance?

**Comment by dev-yohan** [comment]
I have the same issue, what you did?? Thanks a lot
