### ISSUE TITLE
OAuth::RequestProxy::UnknownRequestType (ActionDispatch::Request) (rails3 branch)

### ISSUE THREAD

**Issue by aukevs** [pelle/oauth-plugin#15]
comes up when implementing oauthenticate in my EventsController. 

Maybe the oauth gem doesn't recognize ActionDispatch::Request as a valid RequestProxy because it's new in rails3? Or did i make a mistake during implementation?

Been fighting with this for half a day :)

**Comment by pelle** [comment]
Use my branch of the oauth gem http://github.com/pelle/oauth

It has a fix which I have submitted.

**Comment by aukevs** [comment]
pelle, I love YOU! :) thanks so much for all the hard work on the oauth gems. you just made my day!

**Comment by aukevs** [comment]
ok celebrated to early ;) doesn't work here. Did you add a RequestProxy for ActionDispatch::Request here: http://github.com/pelle/oauth/tree/master/lib/oauth/request_proxy/ it's not in your branch i guess...

**Comment by pelle** [comment]
Ah, you might have solved my last remaining bug I'm having with it. I got it working on the Client for test use.

I'll have a go at it in the morning. I'd like to package it up this weekend and ship it.

**Comment by aukevs** [comment]
Sweet looking forward to it, good luck!
