### ISSUE TITLE
oAuth2 Support for Rails 2.3.5?

### ISSUE THREAD

**Issue by mediavrog** [pelle/oauth-plugin#19]
Hi there,

i'm currently evaluating the use of an oauth gem to have oAuth Provider functionality. I saw that oAuth 2 ist supported in your gem, but only in the branch "rails3". Is the code in this branch somewhat compat to rails 2 or is support for oAuth 2 planned in the master branch?

Thanks for your help

**Comment by pelle** [comment]
It should work well within Rails 2.3.x but I would like to hear feedback about it. I should really rename the branch.

**Comment by mediavrog** [comment]
Thank you so much for this information. I'll report back when i got it set up.
