### ISSUE TITLE
OAuth-plugin assumes OAuth credentials should be associated with User model

### ISSUE THREAD

**Issue by yonkeltron** [pelle/oauth-plugin#23]
We would like to use the OAuth-plugin gem for a model other than User. Looking at the code, we are unsure what it would take to modify the codebase to support such a feature. We were hoping for some guidance on whether or not the architecture can even tolerate such an adaptation (for example, we noticed it depends on current_user). 

Can you offer insight into:
- Whether this configurability is a planned feature
- How to go about taking a stab at adapting the code base

Thanks!

**Comment by pelle** [comment]
Are you talking about the provider or consumer part of the gem? Also do you have any specific usecases?

**Comment by yonkeltron** [comment]
Specifically, the consumer part of the gem. We can think of two use cases, one where the equivalent of the User model isn't named User but might be Person or Customer. The second use case is one where the OAuth credentials should be associated with a group of users rather than an individual user. Imagine a group of people with shared access to a communal photo sharing account. 

Does this clear things up? Thanks!

**Comment by pelle** [comment]
Have a look at the latest code in the 0_4-branch it moves most of the user specific code into the generated model, which would make it easy to remove the user mapping or map it to something else.

**Comment by yonkeltron** [comment]
Thanks, I'll have a peek and I appreciate the opportunity for dialogue.

**Comment by deiga** [comment]
@pelle The Token module still depends on a User model, is there any way to override that?
