### ISSUE TITLE
Proper bundler support.

### ISSUE THREAD

**Issue by libc** [pelle/oauth-plugin#25]
Hello,

When you add to the Gemfile:
    gem 'oauth-plugin', '~> 0.4.1.pre1'

It requires the lib/oauth-plugin.rb by default (which is empty). And there's no way to require rails/init, because it is outside of the lib directory.

 Could you move the rails/init.rb file to the lib directory? So at least I could write something like:
    gem 'oauth-plugin', '~> 0.4.1.pre1', :require => 'oauth/rails'

Thank you,

**Comment by cookrn** [comment]
vendoring the plugin locally within the project fixed this inclusion issue for me - still trying to get all the tests passing though

**Comment by pelle** [comment]
This should now be fixed in the latest pre release gem.

**Comment by libc** [comment]
Thanks, pelle
