### ISSUE TITLE
Mongoid Issue with @consumer.find_by_user_id

### ISSUE THREAD

**Issue by 3en** [pelle/oauth-plugin#27]
The issue is with this line:

```
@token=@consumer.find_by_user_id current_user.id
```

Line 71, lib/oauth/controllers/consumer_controller.rb
https://github.com/pelle/oauth-plugin/blob/master/lib/oauth/controllers/consumer_controller.rb

Mongoid does not recognise this. 

```
undefined method `find_by_user_id' for LinkedinToken:Class
```

Solution is to override or change this line to

```
@token=@consumer.find(:first, :conditions=>{:user_id=>current_user.id.to_s})
```

**Comment by pelle** [comment]
Thanks. Fixed it.
