### ISSUE TITLE
No such file to load, uninitialized constant

### ISSUE THREAD

**Issue by skyporter** [pelle/oauth-plugin#30]
Hi,

Many thanks for your working around oauth.

I was realy excited to use this gem but I had 2 major problem for using the oauth consumer.
1. (resolved) It's write anywhere in doc that the rails generate commande line should have a additional argument to working, otherwise this error occurs and stop process
   
   <pre>
   C:\oauth_plugin>rails g oauth_consumer
     invoke  active_record
     create    app/models/consumer_token.rb
     create    db/migrate/20101214142735_create_oauth_consumer_tokens.rb
     create  config/initializers/oauth_consumers.rb
     create  app/controllers/oauth_consumers_controller.rb
     invoke  erb
   <b>No value provided for required arguments 'name'</b>
   </pre>
   
   Change "rails g oauth_consumer" to "rails g oauth_consumer <b>oauth</b>"  to avoid errror. (I don't know where this arguement is used ??!? ).
2. An then, when I have setup my oauth controller, oauth model and OAUTH_CREDENTIALS. I have the following error on url http://127.0.0.1:3000/oauth_consumers/
   <pre>
   LoadError in Oauth consumersController#index

no such file to load -- json
</pre>
And when I'm going to http://127.0.0.1:3000/oauth_consumers/google :

<pre>
NameError in Oauth consumersController#show

uninitialized constant GoogleToken
</pre>

I'm a forum explorer rather than ruby senior developper, So I didn't found any post about this problem relative to oauth_plugin. Can you please help me ? 

My config:
Windows 7
ruby 1.8.7
rails 3.0.3
oauth 0.4.4
oauth-plugin 0.4.0.pre3

**Comment by amiuhle** [comment]
I have exactly the same problem, and haven't figured it out yet :(

**Comment by amiuhle** [comment]
I'm getting closer.

After adding the following two lines to my Gemfile, I'm getting redirected to Twitter, which does the OAuth and redirects me back:

gem "json"
gem "twitter"

However, on the redirected path (/oauth_consumers/twitter/callback) I get an "Unknown action" error (The action 'callback' could not be found for OauthConsumersController). Trying to work that out now.

**Comment by skyporter** [comment]
Hi amiuhle,

Yeah adding the gem fix the no such file to load problem.

But I have the same problem with the callback action.

Moreover I tried to use the google consumer. And additional gem are requiered :-(. I think i will using the omniauth gem that is provided with a great tutoriel (http://railscasts.com/episodes/236-omniauth-part-2).

**Comment by amiuhle** [comment]
Skyporter,

thanks for the hint, having a Railscast surely helps a lot.
Looking into it right now!
- amiuhle
