### ISSUE TITLE
views and routes not getting created on generate oauth_provider

### ISSUE THREAD

**Issue by Jasrags** [pelle/oauth-plugin#43]
It seems that when i run rails g oauth_provider i get the following:

$ /usr/local/bin/rails g oauth_provider 
      invoke  mongoid
      create    app/models/client_application.rb
      create    app/models/oauth_token.rb
      create    app/models/request_token.rb
      create    app/models/access_token.rb
      create    app/models/oauth2_token.rb
      create    app/models/oauth2_verifier.rb
      create    app/models/oauth_nonce.rb
      create  app/controllers/oauth_controller.rb
      create  app/controllers/oauth_clients_controller.rb
      invoke  test_unit
      create    test/oauth_controller_test_helper.rb
      create    test/functional/oauth_controller_test.rb
      create    test/functional/oauth_clients_controller_test.rb
      create    test/unit/client_application_test.rb
      create    test/unit/oauth_token_test.rb
      create    test/unit/oauth_nonce_test.rb
      invoke  erb
No value provided for required arguments 'name'

but it seems to skip generation of the views and routes that it seems should be created when i look at the generator https://github.com/pelle/oauth-plugin/blob/rails3/generators/oauth_provider/oauth_provider_generator.rb

here is the relevent info from my gem file:
gem 'rails', '3.0.4'
gem 'mongoid', '2.0.0.beta.20'
gem 'bson_ext', '>= 1.2.1'
gem 'devise', '1.1.3'
gem 'oauth', :git => "http://github.com/pelle/oauth.git", :require => 'oauth/server'
gem "oauth-plugin", :git => 'https://github.com/pelle/oauth-plugin.git', :branch => 'rails3'

Any ideas?

**Comment by Jasrags** [comment]
oauth_consumer seems to do the same thing, no views or routes generated

**Comment by Jasrags** [comment]
ok so, need to do a rails g oauth_provider provider for the views and routes to show up. The more you know.

**Comment by airios** [comment]
Better yet, rails g oauth_provider oauth is the best way to generate the necessary items to get this to work.
