### ISSUE TITLE
The action 'callback' could not be found for OauthConsumersController

### ISSUE THREAD

**Issue by wallezhang** [pelle/oauth-plugin#44]
Hi~
  I want to connect with an oauth provider. I follow the instruction step by step, however  on the redirected path (/oauth_consumers/sina/callback) I get an "Unknown action" error (The action 'callback' could not be found for OauthConsumersController). 

What should I do?
Thanks a lot!

**Comment by joybro** [comment]
Hi, hot88zh.

I was suffering from the same problem, but not anymore.
A bug patch about it was committed to trunk about a month ago.

Refer to https://github.com/3en/oauth-plugin/commit/e01655bb9d71482235758ab51f563fd6a7d4e9b4

My oauth-plugin works well after I patched it to my oauth_consumers_controller.rb

Good Luck.

**Comment by wallezhang** [comment]
oh!~it does work! Thanks joybro :)
