### ISSUE TITLE
undefined method `consumer_tokens'

### ISSUE THREAD

**Issue by dsample** [pelle/oauth-plugin#54]
I've been having a few issues with getting the consumer working properly.  I first had to run the generator with any extra parameter to get it to generate the views, I then had to add the references routes manually:

```
resources :oauth_consumers do
    get :callback, :on => :member
end
```

As well as the callback method to the controller:

```
def callback
    super
end
```

I've created my own token class to support Dopplr (pretty much a copy of the TwitterToken class)

```
require 'dopplr'
class DopplrToken < ConsumerToken
  TRIPIT_SETTINGS={
    :site=>"https://www.dopplr.com",
  }

  def self.consumer
    @consumer||=OAuth::Consumer.new credentials[:key],credentials[:secret],TRIPIT_SETTINGS
  end

  def self.client
    unless @client
      @dopplr_oauth=Dopplr::OAuth.new DopplrToken.consumer.key,DopplrToken.consumer.secret
      dopplr_oauth.authorize_from_access token,secret
      @client=Dopplr::Base.new(@dopplr_oauth)
    end

    @client
  end
end
```

I've added the line to the user model:

```
has_one :dopplr, :class_name=>"DopplrToken", :dependent=>:destroy
```

But now I get this error when I'm redirected to the callback URL:

```
Undefined method `consumer_tokens' for #<User:0x103335848>
```

Adding `has_many :consumer_tokens` to the user model made the callback work, but now there's 'Consumer' listed on the index page, rather than identifying it as Dopplr.  Is there something wrong with the callback method that doesn't identify the service class properly?

**Comment by dsample** [comment]
I've fixed this now, I thought I was using version 0.4.0.pre4, but adding `:git => 'https://github.com/pelle/oauth-plugin.git'` to my Gemfile and doing a `bundle update` to get pre5 made it work.

**Comment by pelle** [comment]
Cool. I was worrying what was going on.
