### ISSUE TITLE
Ruby 1.9.2, Rails 3.0.7: Cannot install oauth-plugin

### ISSUE THREAD

**Issue by dalizard** [pelle/oauth-plugin#64]
Hello, I'm trying to install the auth-plugin by following the instructions, but I get the following error after adding 

`gem "oauth-plugin", ">=0.4.0.pre1"` to Gemfile and running `bundle install`

```
cp: /home/users/dimitar/.bundler/tmp/1074/gems/oauth-plugin-0.4.0.pre4 and /home/users/dimitar/.bundler/tmp/1074/gems/oauth-plugin-0.4.0.pre4 are identical (not copied).
cp: /home/users/dimitar/.bundler/tmp/1074/specifications/oauth-plugin-0.4.0.pre4.gemspec and /home/users/dimitar/.bundler/tmp/1074/specifications/oauth-plugin-0.4.0.pre4.gemspec are identical (not copied).
```

`bundle show` gives out:

```
Gems included by the bundle:
Could not find oauth-plugin-0.4.0.pre4 in any of the sources
```

If I go with just `gem "oauth-plugin"` in the Gemfile, the gem installs okay, but then I am unable to generate OAuth and OAuth controllers:

```
$ rails generate oauth_consumer
Could not find generator oauth_consumer.
```

Any suggestions?

**Comment by danielgeri** [comment]
I have the same issue. Any luck?

**Comment by pelle** [comment]
Try using gem "oauth-plugin", ">=0.4.0.pre5"

**Comment by dalizard** [comment]
I am closing this, it's 2019 😄
