### ISSUE TITLE
no routes defined by the generators

### ISSUE THREAD

**Issue by stream7** [pelle/oauth-plugin#70]
Hi,

I get no routes defined after running the generators (for both consumer/producer). 
Even if I define the basic routes for my oauth_consumers_controller the named routes of the lib/oauth/controllers/consumer_controller (and the rest of course) remain undefined.

I'm using ruby 1.8.7 MRI and rails 3.0.4.

Any ideas what the problem might be?

**Comment by Gurpartap** [comment]
```
$ rails generate oauth_provider oauth # will generate provider, including injecting routes.
```

**Comment by stream7** [comment]
... thanks
