### ISSUE TITLE
retrieving credentials from ConsumerToken 

### ISSUE THREAD

**Issue by afeld** [pelle/oauth-plugin#71]
So inside of the `TwitterToken#client` method, I am getting the follow error when trying to authorize:

```
undefined local variable or method `credentials' for #<TwitterToken:0x420ce6ac>
```

I threw in some debugger statements and was strangely able to access `credentials` from within `TwitterToken.consumer` - i.e. only from the class but not from the instance.  Any idea how I might get around this?  I tried `self.class.credentials`, but no dice.

**Comment by Rshomali** [comment]
did you find out a solution for this ?

Thanks

**Comment by afeld** [comment]
havent looked at recent changes to ConsumerToken, but at the time i couldnt do it without patching the ConsumerToken itself.  @pelle, thoughts?

**Comment by joost** [comment]
Put this in your consumer_token.rb:

``` ruby
  # Make credentials also available for objects.
  # Needed to make TwitterToken work.
  def credentials
    self.class.send(:credentials)
  end
```

OR create a twitter_token.rb model in your app and add self. on the line in the client method:

``` ruby
      if credentials[:client].to_sym==:oauth_gem  
```
