### ISSUE TITLE
grant_type option

### ISSUE THREAD

**Issue by jamierytlewski** [pelle/oauth-plugin#72]
I've been trying to find it in the code, but I can't seem to find out where it needs to go, but I think another option that needs to be added to the OAUTH_CREDENTIALS is for grant_type. They grant_type does not seem to be passed along. One of the APIs that I use is requiring the grant_type now. That is the one that is not working with the plugin. I have no problem with Foursquare, which doesn't use the grant_type, but Runkeeper does. I know people brought it up as an issue here:

https://github.com/intridea/oauth2/issues/34

I am getting the same error and most of the suggestions was to put in the grant_type.

**Comment by jamierytlewski** [comment]
This was something silly on my part...I figured it out now.

**Comment by maysam** [comment]
so what is the answer?
