### ISSUE TITLE
OAuth 2.0 Consumer support?

### ISSUE THREAD

**Issue by bradyhigginbotham** [pelle/oauth-plugin#89]
I can't seem to find if the oauth-plugin gem completely supports OAuth 2.0 for consumer apps. While the README states support exists, I'm hesitant as I don't know if that is experimental or full 2.0 support.

Any help would be greatly appreciated.

**Comment by pelle** [comment]
Yes it does support OAuth 2.0 see the example in oauth_config. 

You will need to use the 0.4.0 pre release though. Use 0.4.0.rc1 in your Gemfile
