### ISSUE TITLE
two-legged?

### ISSUE THREAD

**Issue by ghost** [pelle/oauth-plugin#9]
Has anyone modified this to support two-legged oauth?
Any tips/advice/code?

**Comment by brugidou** [comment]
Hi,

I did a very simple thing for 2 legged (without token), just add:

```
before_filter :verify_oauth_consumer_signature
```

this will simply check that the request is sent from a valid client application and sets the current_client_application.

From my understanding, 2-legged oauth is just oauth without a token. Let me know if that's what you wanted.

**Comment by PRX** [comment]
Thanks - I found that after I wrote you - and I now have it working!
